# Site
repository: ssimx/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Simon Simić
title: Full Stack Web Developer
email: simicsimon99@gmail.com
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  ssimx
instagram_username: simonsimic_
linkedin_username: simon-simic

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Živijo, ime mi je Simon in sem Junior Full Stack Web Developer. Poleg programiranja, imam izkušnje tudi kot sistemski administrator.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Tweetly
        link: tweetly-ten.vercel.app
        # link_text: Project Website
        additional_links:
          - title:  ssimx/tweetly
            icon: fab fa-github
            url: github.com/ssimx/tweetly
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Sodobna aplikacija za družbena omrežja, ki posnema osnovno funkcionalnost X-a (prej znanega kot Twitter)
        description: | # this will include new lines to allow paragraphs
          Ta projekt sem zaštartal z namenom, da bi razširil znanje o Reactu z učenjem enega izmed sodobnih frameworkov in sicer odločil sem se za NextJs, saj je trenutno zelo "in".
          Poleg front-end programiranja sem se zanimal tudi za back-end, zato sem se odločil za implementacijo ločenega API-ja z uporabo NodeJs & ExpressJs in PostgreSQL & Prisma ORM tech stacka.
          Za izdelavo te aplikacije sem potreboval 6 mesecev, naučil sem se veliko novih veščin in zelo sem ponosen, da lahko prikažem malo bolj resen projekt v svojem portfelju.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
